let btn = document.getElementById('btn');
let output = document.getElementById('output');
let quotes = 
    [
        'No se puede encontrar la paz evitando la vida. (Virginia Woolf)', 'El pesimista se queja del viento; el optimista espera que cambie; el realista ajusta las velas. (William George Ward)', 'Vale más actuar exponiéndose a arrepentirse de ello, que arrepentirse de no haber hecho nada. (Giovanni Boccaccio)',  'No deseo que las mujeres tengan poder sobre los hombres, sino sobre ellas mismas. (Mary Wollstonecraft)', 'Los pecados escriben la historia, el bien es silencioso. (Goethe)',  'La felicidad se alcanza cuando lo que uno piensa, lo que uno dice y lo que uno hace, están en armonía. (Mahatma Gandhi)',  'La historia se repite, ese es uno de los errores de la historia. (Charles Darwin)', 'Aprende a dejar ir. Esa es la clave de la felicidad. (Buda)', 'No sé con qué armas se peleará la tercera guerra mundial, pero la cuarta será con palos y piedras. (Albert Einstein)', 'Hay dos maneras de vivir tu vida: una como si nada es un milagro, la otra es como si todo es un milagro. (Albert Einstein)', 'Vence la ira con serenidad. Vence la maldad con bondad. Vence el egoísmo con generosidad. Vence la deshonestidad con verdad. (Buda)',  'Hay dos clases de hombres: quienes hacen la historia y quienes la padecen. (Camilo José Cela)',  'La raíz del sufrimiento es el apego. (Buda)',  'Sé el cambio que quieres ver en el mundo. (Mahatma Gandhi)', 'Hay verdades que no son para todos los hombres, ni para todos los tiempos. (Voltaire)',  'En los momentos de crisis, sólo la imaginación es más importante que el conocimiento. (Albert Einstein)',  'El hombre que más ha vivido no es aquél que más años ha cumplido, sino aquel que más ha experimentado la vida. (Jean Jacques Rousseau)', 'La vida es un diez por ciento como la hacemos y un noventa por ciento como la tomamos. (Irving Berlin)', 'Un amigo fiel es un alma en dos cuerpos. (Aristóteles)', 'El único hombre que no se equivoca es el que nunca hace nada. (Goethe)', 'La duda es la madre de la invención. (Galileo Galilei)',
         ];
btn.addEventListener('click', function(){
    var randomQuote = quotes[Math.floor(Math.random() * quotes.length)]
    output.innerHTML = randomQuote;
})    
